# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kf/Prog/GitHub/Movie2scan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kf/Prog/GitHub/Movie2scan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kf/Prog/GitHub/Movie2scan/CMakeFiles /home/kf/Prog/GitHub/Movie2scan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kf/Prog/GitHub/Movie2scan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named movie2scan

# Build rule for target.
movie2scan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 movie2scan
.PHONY : movie2scan

# fast build rule for target.
movie2scan/fast:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/build
.PHONY : movie2scan/fast

movie2scan/main.o: movie2scan/main.cpp.o
.PHONY : movie2scan/main.o

# target to build an object file
movie2scan/main.cpp.o:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/movie2scan/main.cpp.o
.PHONY : movie2scan/main.cpp.o

movie2scan/main.i: movie2scan/main.cpp.i
.PHONY : movie2scan/main.i

# target to preprocess a source file
movie2scan/main.cpp.i:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/movie2scan/main.cpp.i
.PHONY : movie2scan/main.cpp.i

movie2scan/main.s: movie2scan/main.cpp.s
.PHONY : movie2scan/main.s

# target to generate assembly for a file
movie2scan/main.cpp.s:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/movie2scan/main.cpp.s
.PHONY : movie2scan/main.cpp.s

src/HyDataHandler.o: src/HyDataHandler.cpp.o
.PHONY : src/HyDataHandler.o

# target to build an object file
src/HyDataHandler.cpp.o:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyDataHandler.cpp.o
.PHONY : src/HyDataHandler.cpp.o

src/HyDataHandler.i: src/HyDataHandler.cpp.i
.PHONY : src/HyDataHandler.i

# target to preprocess a source file
src/HyDataHandler.cpp.i:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyDataHandler.cpp.i
.PHONY : src/HyDataHandler.cpp.i

src/HyDataHandler.s: src/HyDataHandler.cpp.s
.PHONY : src/HyDataHandler.s

# target to generate assembly for a file
src/HyDataHandler.cpp.s:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyDataHandler.cpp.s
.PHONY : src/HyDataHandler.cpp.s

src/HyLayersMesher.o: src/HyLayersMesher.cpp.o
.PHONY : src/HyLayersMesher.o

# target to build an object file
src/HyLayersMesher.cpp.o:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyLayersMesher.cpp.o
.PHONY : src/HyLayersMesher.cpp.o

src/HyLayersMesher.i: src/HyLayersMesher.cpp.i
.PHONY : src/HyLayersMesher.i

# target to preprocess a source file
src/HyLayersMesher.cpp.i:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyLayersMesher.cpp.i
.PHONY : src/HyLayersMesher.cpp.i

src/HyLayersMesher.s: src/HyLayersMesher.cpp.s
.PHONY : src/HyLayersMesher.s

# target to generate assembly for a file
src/HyLayersMesher.cpp.s:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyLayersMesher.cpp.s
.PHONY : src/HyLayersMesher.cpp.s

src/HyNode.o: src/HyNode.cpp.o
.PHONY : src/HyNode.o

# target to build an object file
src/HyNode.cpp.o:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyNode.cpp.o
.PHONY : src/HyNode.cpp.o

src/HyNode.i: src/HyNode.cpp.i
.PHONY : src/HyNode.i

# target to preprocess a source file
src/HyNode.cpp.i:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyNode.cpp.i
.PHONY : src/HyNode.cpp.i

src/HyNode.s: src/HyNode.cpp.s
.PHONY : src/HyNode.s

# target to generate assembly for a file
src/HyNode.cpp.s:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyNode.cpp.s
.PHONY : src/HyNode.cpp.s

src/HyScanner.o: src/HyScanner.cpp.o
.PHONY : src/HyScanner.o

# target to build an object file
src/HyScanner.cpp.o:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyScanner.cpp.o
.PHONY : src/HyScanner.cpp.o

src/HyScanner.i: src/HyScanner.cpp.i
.PHONY : src/HyScanner.i

# target to preprocess a source file
src/HyScanner.cpp.i:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyScanner.cpp.i
.PHONY : src/HyScanner.cpp.i

src/HyScanner.s: src/HyScanner.cpp.s
.PHONY : src/HyScanner.s

# target to generate assembly for a file
src/HyScanner.cpp.s:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyScanner.cpp.s
.PHONY : src/HyScanner.cpp.s

src/HyTriangle.o: src/HyTriangle.cpp.o
.PHONY : src/HyTriangle.o

# target to build an object file
src/HyTriangle.cpp.o:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyTriangle.cpp.o
.PHONY : src/HyTriangle.cpp.o

src/HyTriangle.i: src/HyTriangle.cpp.i
.PHONY : src/HyTriangle.i

# target to preprocess a source file
src/HyTriangle.cpp.i:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyTriangle.cpp.i
.PHONY : src/HyTriangle.cpp.i

src/HyTriangle.s: src/HyTriangle.cpp.s
.PHONY : src/HyTriangle.s

# target to generate assembly for a file
src/HyTriangle.cpp.s:
	$(MAKE) -f CMakeFiles/movie2scan.dir/build.make CMakeFiles/movie2scan.dir/src/HyTriangle.cpp.s
.PHONY : src/HyTriangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... movie2scan"
	@echo "... rebuild_cache"
	@echo "... movie2scan/main.o"
	@echo "... movie2scan/main.i"
	@echo "... movie2scan/main.s"
	@echo "... src/HyDataHandler.o"
	@echo "... src/HyDataHandler.i"
	@echo "... src/HyDataHandler.s"
	@echo "... src/HyLayersMesher.o"
	@echo "... src/HyLayersMesher.i"
	@echo "... src/HyLayersMesher.s"
	@echo "... src/HyNode.o"
	@echo "... src/HyNode.i"
	@echo "... src/HyNode.s"
	@echo "... src/HyScanner.o"
	@echo "... src/HyScanner.i"
	@echo "... src/HyScanner.s"
	@echo "... src/HyTriangle.o"
	@echo "... src/HyTriangle.i"
	@echo "... src/HyTriangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

